### ISSUE TITLE
C# wrapper for wolfPKCS11 ?

### ISSUE THREAD

**Issue by fliot** [wolfSSL/wolfPKCS11#31]
Is there an "easy way" to use wolfPKCS11 in C# on windows, to handle a mutual TLS client based on a HSM token ?

**Comment by dgarske** [comment]
Hi @fliot ,

Thank you for your interest in our wolfPKCS11 provider. Can you tell us more about your project?

We do have some PKCS11 TLS examples that might be helpful:
TLS Server: https://github.com/wolfSSL/wolfssl-examples/tree/master/pkcs11#tls-server-example-with-pkcs-11-rsa
TLS Client:: https://github.com/wolfSSL/wolfssl-examples/pull/460

We have a Visual Studio solution with examples here: https://github.com/wolfSSL/wolfPKCS11/tree/master/IDE/VisualStudio
At this time we haven't added any C# interfaces. I wolfCrypt/wolfSSL we have (see https://github.com/wolfSSL/wolfssl/tree/master/wrapper/CSharp and PR https://github.com/wolfSSL/wolfssl/pull/3166).

If you'd like to setup a call to discuss please email facts at wolfssl dot com and reference this git issue and let us know where you are located.

Thanks,
David Garske, wolfSSL

**Comment by fliot** [comment]
I was wondering if it was possible with current code,
Not looking for consulting or custom development, but I thank you for the helpful answer.
Thanks,
Regards.
